# Generated by Django 4.0.3 on 2022-03-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_purpose', models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT'), ('Projects', 'Projects')], max_length=30)),
                ('property_types', models.CharField(choices=[('Homes', 'Homes'), ('Plots', 'Plots'), ('Commercial', 'Commercial')], max_length=30)),
                ('aria_unit', models.CharField(choices=[('Square Feet', 'Square feet'), ('Square meter', 'Square meter'), ('Square Yards', 'Square Yards'), ('Marla', 'Marla'), ('Kanal', 'Kanal')], max_length=30)),
                ('aria_size', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=255)),
                ('instalment', models.BooleanField(default=False)),
                ('listining_expiry', models.CharField(choices=[('1 Month', '1 Month'), ('3 Month', '3 Month'), ('6 Month', '6 Month')], max_length=30)),
                ('property_name', models.CharField(max_length=255)),
                ('property_description', models.CharField(max_length=900)),
                ('property_type_img', models.ImageField(upload_to='uploads/property_type/%y')),
                ('property_docunments', models.FileField(upload_to='uploads/property_docunments/%y')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(upload_to='uploads/propety/%y')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.property')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_description', models.TextField()),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('appoinment_status', models.CharField(choices=[('Approved', 'Approved'), ('pending', 'pending')], max_length=30)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
